Return non-200 HTTP response code if concurrent API requests cross middleware.concurrent-request-limit
observatorium/observatorium pull request #130
Opened 2021-03-16 12:15 UTC by spaparaju

With Zero backlog and backlog getting timing out immediately with 1ms, all concurrent requests beyond 'middleware.concurrent-request-limit' result in immediate non-200 HTTP response

2021-03-16 12:25 UTC, squat commented on main.go
> +		backlogDuration, _ := time.ParseDuration("1ms")
Rather than parsing a string, which can return an error, let's use `time.Millisecond` directly

2021-03-16 15:10 UTC, kakkoyun requested changes
This change makes sense. We should be aware of the possible implications of having a large number of the backlog. As long as we have headroom resource-wise all would be good.

2021-03-16 15:10 UTC, kakkoyun commented on main.go
> +		backlogDuration := 1 * time.Millisecond
Let's make this configurable. We might need to increase this duration without building a new binary.

2021-03-23 13:46 UTC, kakkoyun requested changes
Looking good. Only one thing.

2021-03-23 13:46 UTC, kakkoyun commented on main.go
> +	flag.IntVar(&cfg.middleware.backLogDurationConcurrentRequests, "middleware.backlog-duration-concurrent-requests", 1,
```suggestion
	flag.DurationVar(&cfg.middleware.backLogDurationConcurrentRequests, "middleware.backlog-duration-concurrent-requests", time.Millisecond,
```

We have a duration type let's use it

2021-03-29 11:11 UTC, kakkoyun approved these changes

2021-03-29 11:11 UTC, merged